name: test

on:
  release:
    types: [published]

jobs:
  generate-file:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: setup
        run: |
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git config --global user.name $GITHUB_ACTOR
          git fetch
          git checkout main
      - name: save file
        run: |
          echo "test" >> test.txt
          git add .
          git commit -m 'add test value'
          git push origin main
